name = "poe-skins"
main = "worker/index.js"
compatibility_date = "2025-05-01"

[assets]
directory = "./dist"
binding = "ASSETS"

[[routes]]
pattern = "fungamingvn.shop/*"
zone_name = "fungamingvn.shop"

[[routes]]
pattern = "www.fungamingvn.shop/*"
zone_name = "fungamingvn.shop"
